### ISSUE TITLE
Adding support for XML in SoySauceViewRenderer

### ISSUE THREAD

**Issue by lpellegr** [micronaut-projects/micronaut-views#159]
I am using Closure Templates with Micronaut Views. The experience is quite positive but it seems I am experiencing a limitation when rendering an XML view. Let me explained further.

I have a use case that requires rendering an Atom/RSS feed view based on a soy template. My Micronaut controller has a method annotated as follows:

```java
@Get("/{feedSlug}.rss")
@Produces(value = MediaType.APPLICATION_XML)
public HttpResponse<ModelAndView<Map<String, Object>>> rssFeedByDomain() { ... }
```

When I invoke the resource, the view is rendered with as content:

> io.micronaut.views.ModelAndView@2240920f

To get the response object _ModelAndView_ rendered as expected, I need to use a custom version of micronaut-views with the class _SoySauceViewsRenderer_ defining:

```java
@Produces({MediaType.TEXT_HTML, MediaType.APPLICATION_XML})
```

instead of:

```java
@Produces(MediaType.TEXT_HTML)
```

Is there a reason not to support this format with Closure Templates? if no, would it be possible to add support for XML rendering? this could benefit a wider community.

**Comment by graemerocher** [comment]
Contributions welcome!
