### ISSUE TITLE
Kotlin data class not binding with Thymeleaf

### ISSUE THREAD

**Issue by cosmin-marginean** [micronaut-projects/micronaut-views#206]
### Steps to Reproduce

To reproduce this, (create an empty Kotlin Micronaut app, etc) create `resources/views/home.html` with this content:
```html
<!DOCTYPE html>
<html lang="en" xmlns:th="http://www.thymeleaf.org">
<head>
    <title>Home</title>
</head>
<body>
Text: <span th:text="${txt}">None</span>
</body>
</html>
```

Create the controller (Kotlin):

```kotlin
@Secured(SecurityRule.IS_ANONYMOUS)
@Controller("/views")
class AuthController {

    @View("home")
    @Get("/home")
    fun home() : HttpResponse<Any> {
        return HttpResponse.ok(HomePageData("My Text"))
    }
}

data class HomePageData(val txt:String)
```

Then call http://localhost:8080/views/home

### Expected Behaviour

We expect the `txt` field to be bound and accessible in the view.

### Actual Behaviour

The field is not rendered:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Home</title>
</head>
<body>
Text: <span></span>
</body>
</html>
```

However, if we respond with a map, we do get the expected result:

```kotlin
fun home() : HttpResponse<Any> {
    return HttpResponse.ok(mapOf("txt" to "My text"))
}
```
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Home</title>
</head>
<body>
Text: <span>My text</span>
</body>
</html>
```

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 2.4.0
- **JDK Version:** 11

I can't tell if this is a binding issue with Thymeleaf or an issue with Micronaut views, but I thought someone here can shine a light on that.

**Comment by cosmin-marginean** [comment]
After further investigation we found this:

> Use the @Introspected annotation on your POJO object to avoid reflection at runtime (It will also fix a problem with OpenJ9 jvm.)

from here: https://micronaut-projects.github.io/micronaut-views/latest/guide/

It would be good to know what exactly is the bug with the OpenJ9 JVM that this is referring to, as that seems to be the issue in our case.

**Comment by sdelamo** [comment]
Can we close this issue @cosmin-marginean  ?

**Comment by cosmin-marginean** [comment]
Yes, I believe we can, the solution is there in the update.
