### ISSUE TITLE
POJOs passed to views are not being processed by ViewModelProcessors

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-views#247]
@rferreira 

> ModelViewProcessors are not applied to non-map like models due to its strict Map<String, Object> interface. We should consider revisiting this in favor of a <T> interface for v3

Context for this issue:

https://github.com/micronaut-projects/micronaut-views/pull/219  and: https://github.com/micronaut-projects/micronaut-views/pull/246

Maybe we can use [BeanIntrospection](https://docs.micronaut.io/latest/guide/#introspection) to support processing Models which are POJOs annotated with `@Introspected`

**Comment by sdelamo** [comment]
@rferreira would you be interested in contributing this feature? I assure you the PR review will be much faster this time. 😔

**Comment by rferreira** [comment]
Yup! I think I know what needs to be done here, just give a couple of weeks.
