### ISSUE TITLE
Log a warning if view is not found

### ISSUE THREAD

**Issue by debuglevel** [micronaut-projects/micronaut-views#25]
I recently referenced a @View("with-a-typo") and wondered, why I just got a 404. It seems like a missing view is logged as DEBUG. It might be nicer to log a WARN or even more severe, as a missing view usually stops `micronaut-view` from what it should do.

(I *think* that's the line; but I just did a quick search on github and did not verify it)
https://github.com/micronaut-projects/micronaut-views/blob/1962ef4928b97fad5157afcd9147b719621c2018/views-core/src/main/java/io/micronaut/views/ViewsFilter.java#L138

Furthermore, I wonder if this is a real 404 (resource requested by the user is not found) or rather a 500 (something on the server side is broken).

**Comment by graemerocher** [comment]
I actually think this should be an exception if a view is specified but not found
