### ISSUE TITLE
Soy Conflict in 1.3

### ISSUE THREAD

**Issue by jamesward** [micronaut-projects/micronaut-views#28]
I added the deps:
```
implementation("io.micronaut:micronaut-views:1.3.0")
runtimeOnly("org.thymeleaf:thymeleaf:3.0.11.RELEASE")
```

And tried to start my project but got an error:
```
Unexpected error occurred: Multiple possible bean candidates found: [io.micronaut.views.soy.SoySauceViewsRenderer, io.micronaut.views.soy.SoyTofuViewsRenderer, io.micronaut.views.thymeleaf.ThymeleafViewsRenderer]
io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [io.micronaut.views.soy.SoySauceViewsRenderer, io.micronaut.views.soy.SoyTofuViewsRenderer, io.micronaut.views.thymeleaf.ThymeleafViewsRenderer]
```

Seems like it's trying to use Soy even though I don't want to use Soy.

**Comment by graemerocher** [comment]
Sorry we probably should have documented this better. Change the dependency to micronaut-views-thymeleaf and you should be good to go

**Comment by jamesward** [comment]
Thanks! I was upgrading from `1.2` so that made things tricky.  Changing to `micronaut-views-thymeleaf` resolved the issue.

**Comment by jameskleeh** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-views/commit/ae36ce3667d56ba241cec6176df7cb00bb85d88b
