### ISSUE TITLE
SecurityViewModelProcessor does not populate security key when model is not a Map<>

### ISSUE THREAD

**Issue by kfowler** [micronaut-projects/micronaut-views#286]
### Expected Behavior

According to [the manual](https://micronaut-projects.github.io/micronaut-views/latest/guide/#security-model-enhancement), `SecurityViewModelProcessor` injects the current username in the view. 

This only works for `ModelAndView<T>` where `T` is `Map<String, Object>`.

Configured as described in the linked document, `security` should be present in the view context. E.g.,

```java
    @Produces(MediaType.TEXT_HTML)
    @Get("/good")
    @View("home")
    Map<String, Object> worksForMe(Principal principal) {
        Map<String, Object> result = new HashMap<>();
        result.put("principal", principal);
        return result;
    }
```

Produces:
```
security | {name=sherlock, attributes={}}
param |  
session |  
application
```

### Actual Behaviour

When the model is *not* a `Map`, `SecurityViewModelProcessor` doesn't run and the template context does not have a `security` entry.

```java
    @Produces(MediaType.TEXT_HTML)
    @Get("/bad")
    @View("home")
    AuthInfo doesntWorkForMe(Principal principal) {
        var result = new AuthInfo();
        result.setName(principal.getName());
        return result;
    }
```

```
param |  
-- | --
session |  
application |  
```

### Steps To Reproduce

To Reproduce: 
  - Checkout out the attached repository
  - Good case:
    1) gradle run
    2) visit http://localhost:8080/good
    3) enter 'sherlock'/'password'
    4) see 'security	{name=sherlock, attributes={}}' in output
  - Bad case:
    1) gradle run
    2) visit http://localhost:8080/bad
    3) enter 'sherlock'/'password' (if necessary)
    4) no 'security' & view shows "Unauthenticated"

### Environment Information

Mac OS 11.5.2 / Java 11

### Example Application

https://github.com/kfowler/micronaut-views-issue-286

### Version

3.0.0

**Comment by kfowler** [comment]
This doesn't happen in 2.X because the model is a map by the time the security processor runs.

The code in `ViewsFilter` looks like this:
```java
                    ModelAndView<?> modelAndView = new ModelAndView<>(view, body instanceof ModelAndView ? ((ModelAndView<?>) body).getModel().orElse(null) : body);
                    viewsModelDecorator.decorate(request, modelAndView);
                    Writable writable = optionalViewsRenderer.get().render(view, modelAndView.getModel().orElse(null), request);
```

`ViewsModelDecorator` can't do much w/ the model w/o checking the type at runtime:
```java
public interface ViewsModelDecorator {
    /**
     * decorates a model.
     *
     * @param request      The http request this model relates to.
     * @param modelAndView The ModelAndView to be enhanced.
     */
     void decorate(HttpRequest<?> request, @NonNull ModelAndView<?> modelAndView);
}
```

**Comment by sdelamo** [comment]
Starting [Micronaut Views 3](https://micronaut-projects.github.io/micronaut-views/latest/guide/#breaks) `ViewModelProcessor` are typed. 

> ViewModelProcessor no longer assumes a Map<String,Object> model and must be typed to the exact type of the model you would like to process.

[SecurityViewModelProcessor](https://github.com/micronaut-projects/micronaut-views/blob/master/views-core/src/main/java/io/micronaut/views/model/security/SecurityViewModelProcessor.java) is typed to `Map<String, Objet>`.  I will clarify in the docs that. 

If you want to return a POJO as a model for your view, you could write your own `SecurityViewModelProcessor` to statisfy your needs. Maybe have a parent class which contains a `@Nullable` `Authentication` field which you populate in the view model processor. 

What is your use case?

**Comment by kfowler** [comment]
Thanks for clarifying in the documentation.

The behavior is different from 2.5. In 2.5 `processModel` is called before the decoration, so the model is a map by the time ModelAndView gets decorated.

~

The definition of `ViewsModelDecorator` doesn't really allow for type-safe decoration—i.e., modification of the model or view—because the model and view is typed as `?`. At runtime, the decorator's type is effectively "checked" through the bean-lookup.

```java
public interface ViewsModelDecorator {
    /**
     * decorates a model.
     *
     * @param request      The http request this model relates to.
     * @param modelAndView The ModelAndView to be enhanced.
     */
     void decorate(HttpRequest<?> request, @NonNull ModelAndView<?> modelAndView);
}
```

`ViewsFilter` calls the typed-with-a-wildcard `decorate` and then `render()`:

```java
    public final Publisher<MutableHttpResponse<?>> doFilter(HttpRequest<?> request,
                                                            ServerFilterChain chain) {
        return Flux.from(chain.proceed(request))
            .switchMap(response -> {
                Optional<String> optionalView = viewsResolver.resolveView(request, response);
                if (!optionalView.isPresent()) {
                    LOG.debug("no view found");
                    return Flux.just(response);
                }
                Object body = response.body();
                MediaType type = resolveMediaType(response, body);
                String view = optionalView.get();
                try {
                    Optional<ViewsRenderer> optionalViewsRenderer = viewsRendererLocator.resolveViewsRenderer(view,  type, body);
                    if (!optionalViewsRenderer.isPresent()) {
                        LOG.debug("no view renderer found for media type: {}, ignoring", type.toString());
                        return Flux.just(response);
                    }
                    ModelAndView<?> modelAndView = new ModelAndView<>(view, body instanceof ModelAndView ? ((ModelAndView<?>) body).getModel().orElse(null) : body);
                    viewsModelDecorator.decorate(request, modelAndView);
                    Writable writable = optionalViewsRenderer.get().render(view, modelAndView.getModel().orElse(null), request);
                    response.contentType(type);
                    response.body(writable);
                    return Flux.just(response);
                } catch (ViewNotFoundException e) {
                    return Flux.error(e);
                }
            });
    }
```

I'm using `ThymeleafViewsRenderer` which creates a `context` using `ViewUtils.modelOf()`:

```java
    public Writable render(@NonNull String viewName,
                           @Nullable T data,
                           @NonNull HttpRequest<?> request) {
        ArgumentUtils.requireNonNull("viewName", viewName);
        ArgumentUtils.requireNonNull("request", request);
        return (writer) -> {
            IContext context = new WebContext(request, request.getLocale().orElse(Locale.US), ViewUtils.modelOf(data));
            render(viewName, context, writer);
        };
    }
```

I don't know how other renderers work. In this case, calling `ViewUtils.modelOf(…)` from `ViewsFilter` seems like it would make existing code work*.


* not quite: since `BeanMap.of()` no longer allows reflective bean-mapping.
