### ISSUE TITLE
NonUniqueBeanException after 1.3.0 update

### ISSUE THREAD

**Issue by phxql** [micronaut-projects/micronaut-views#31]
Hi,

i've updated to 1.3.0 and now i get this exception:

```
Multiple possible bean candidates found: [io.micronaut.views.soy.SoySauceViewsRenderer, io.micronaut.views.freemarker.FreemarkerViewsRenderer, io.micronaut.views.soy.SoyTofuViewsRenderer]
```

My dependencies look like this:

```xml
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-views</artifactId>
        </dependency>
        <dependency>
            <groupId>org.freemarker</groupId>
            <artifactId>freemarker</artifactId>
        </dependency>
```

This hasn't happened with 1.2.10. Is there maybe a codition in `SoySauceViewsRenderer` and `SoyTofuViewsRenderer` missing?

I can workaround by setting `micronaut.views.soy.enabled: false` in my config - but this seems like a bug to me.

**Comment by ilopmar** [comment]
Duplicates https://github.com/micronaut-projects/micronaut-views/issues/28

This is a known issue and it will be fixed in the next version. Change your dependency to `micronaut-views-freemarker`.

**Comment by phxql** [comment]
Thanks, sorry for the work.
