### ISSUE TITLE
Convenience method: HttpResponse returning an Optional

### ISSUE THREAD

**Issue by rosemead** [micronaut-projects/micronaut-views#319]
### Feature description

Hi,

Looking for an `HttpResponse` shortcut, producing `OK`+body/`NOT_FOUND` respective of the passed `Optional`. Equivalent to [spring's](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/ResponseEntity.html#of-java.util.Optional-) `ResponseEntity.of(Optional)`.

Many thanks!

**Comment by sdelamo** [comment]
In Micronaut, if a controller's method annotated with, e.g. `@Get` returns an optional. If the Optional is empty, you get a 404. If it is not empty you receive a 200.
