### ISSUE TITLE
JTE 2.0

### ISSUE THREAD

**Issue by edward3h** [micronaut-projects/micronaut-views#371]
### Feature description

JTE released a 2.0 version, so I'd like to implement support for that.

2.0 has breaking changes in template syntax vs. 1.x. I'm wondering about the best design to avoid breaking existing usage (if there is any).

Possibilities I thought of:

* Add a new module views-jte2 which is independent of the existing one.
* Add configuration option in views-jte to specify JTE version.
* Make views-jte detect which JTE version is on the classpath.

Do you have any thoughts on the above?

**Comment by edward3h** [comment]
Sadly I haven't found time to work on this yet.

**Comment by graemerocher** [comment]
If you do then a jte2 module makes sense

**Comment by edward3h** [comment]
This was done.
