### ISSUE TITLE
ModelAndView rendered as JSON in Micronaut 2

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-views#43]
Given this action:

```groovy
@Get("/modelAndView")
Single<ModelAndView> modelAndView() {
    ModelAndView modelAndView = new ModelAndView("home",
            new Person(loggedIn: true, username: 'sdelamo'))
    return Single.just(modelAndView)
}
```

And a freemarker view at `src/main/resources/views/home.ftl`, in Micronaut 1.x the view is rendered with the `ModelAndView` instance bound to it.

In Micronaut 2, it is simply rendered as JSON:

`{"view":"home","model":{"username":"sdelamo","loggedIn":true}}`

**Comment by ilopmar** [comment]
Related https://github.com/micronaut-projects/micronaut-core/issues/2983
