### ISSUE TITLE
@View not working in actions returning reactive types when using Micronaut 2

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-views#44]
Given this action:

```groovy
@View("home")
@Get("/reactive")
Single<Person> reactive() {
    return Single.just(new Person(loggedIn: true, username: 'sdelamo'))
}
```

And a freemarker view at src/main/resources/views/home.ftl, in Micronaut 1.x the view is rendered with the Person instance bound to it.

In Micronaut 2, it is simply rendered as JSON:

`{"username":"sdelamo","loggedIn":true}`

**Comment by jameskleeh** [comment]
@alvarosanchez Can you verify this works now with micronaut-projects/micronaut-core#2983 being complete?

**Comment by alvarosanchez** [comment]
It fails with M3
