### ISSUE TITLE
 Multiple possible bean candidates found: 

### ISSUE THREAD

**Issue by ibmsoft** [micronaut-projects/micronaut-views#47]
message: "Internal Server Error: Multiple possible bean candidates found: [io.micronaut.views.freemarker.FreemarkerViewsRenderer, io.micronaut.views.rocker.RockerViewsRenderer]",

my gradle
    implementation 'io.micronaut:micronaut-views'
    runtime("org.freemarker:freemarker:2.3.28")
micronaut-version:1.3.5
micronaut-views: 1.3.2

**Comment by ilopmar** [comment]
Don't use `implementation 'io.micronaut:micronaut-views'` but the dependency for the technology you want to use. In this case `implementation 'io.micronaut:micronaut-views-freemarker'`
