### ISSUE TITLE
Rendering failures result in ReadTimeoutException instead of returning a proper error response

### ISSUE THREAD

**Issue by viniciusccarvalho** [micronaut-projects/micronaut-views#478]
### Actual Behaviour

If a pebble view template has an error, for instance a simple typo on the syntax:

```{% endlock %}```

The request on the browser gets stuck, no response is ever sent, there is an error on the console but the browser does not get a 500 error for example.

### Version

3.7.4

**Comment by wetted** [comment]
This is a bigger problem than just Pebble. Freemaker fails too. Rendering failures that raise `ViewRenderingException` fail with `ReadTimeoutException`.
