### ISSUE TITLE
Micronaut-views is broken

### ISSUE THREAD

**Issue by jameskleeh** [micronaut-projects/micronaut-views#48]
The `micronaut-views` dependency is not working. Broken in 1.3.2

**Comment by edalex-ian** [comment]
And this would be why upgrading to micronaut 1.3.5 the `VelocityViewsRenderer` can no longer be found?

**Comment by jameskleeh** [comment]
@edalex-ian If you are depending on `micronaut-views`, then yes. Use `micronaut-views-velocity` instead. `micronaut-views` will be removed for 2.0, so it is the better path forward regardless

**Comment by edalex-ian** [comment]
Excellent! Thank you. :+1: 

([The doco](https://micronaut-projects.github.io/micronaut-views/latest/guide/) doesn't seem to mention that, or was I looking at the wrong doco?)

**Comment by ilopmar** [comment]
This was fixed with Micronaut views release 2.0.0
