### ISSUE TITLE
Update docs for 1.3.x

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-views#54]
Update the docs in `1.3.x` to apply the same changes as in `master`. Specifically:

- Remove the usage of `implementation("io.micronaut:micronaut-views")`
- Remove the `runtime` dependencies for every technology and add `implementation("io.micronaut:micronaut-views-xxxxxx")`

**Comment by sdelamo** [comment]
I think this can be closed. @ilopmar Please, reopen if you don't think so.
