### ISSUE TITLE
jte 3

### ISSUE THREAD

**Issue by edward3h** [micronaut-projects/micronaut-views#552]
### Feature description

jte 3.0.0 was released yesterday. It bumps the minimum JDK version to 17. It has a couple of incompatible API changes from version 2.x

I added a model generator which generates a typesafe API for templates. With this we can write code something like 

```java
@Inject Templates templates;

// SNIP

Writer writer = ...
templates.helloWorld("Hi!").render(new WriterOutput(writer));
```

**Comment by edward3h** [comment]
I hope to work on support, but I don't have much spare time so I couldn't commit to a timescale.

**Comment by agentgt** [comment]
@edward3h I owe @casid for how much he has helped me so when I do JStachio support I might be able to do JTE as well or at least help.

**Comment by edward3h** [comment]
@agentgt Thanks! My plan was to copy the jte-models extension module and edit to make it use Micronaut types. i.e. returned models would implement `Writable`, implementations would have `@Singleton` and `@Requires` so they can be injected. Interestingly this means it wouldn't actually depend on micronaut-views library.

I don't think I will get to this any time soon so if you have time go for it.

**Comment by marcospereira** [comment]
@edward3h, I just submitted #617. It is minimal for now, although I plan to improve the docs later. If you have a chance, let me know what you think.
