### ISSUE TITLE
Support @Produces(MediaType.TEXT_PLAIN) in ViewRenderers

### ISSUE THREAD

**Issue by debuglevel** [micronaut-projects/micronaut-views#56]
### Steps to Reproduce
Most (all?) `ViewRenderer`s are annotated with `@Produces(MediaType.TEXT_HTML)`. If one creates a controller with a `@Get("/plaintext", produces = [MediaType.TEXT_PLAIN])` function, the view therefore will not be rendered via the `ViewRenderer`.

### Expected Behaviour
`ViewRenderer`s should be able to render plain text.

### Actual Behaviour
Micronaut Views does not render the data with the ViewRenderer (but returns `toString()` instead?)

### Workaround
Of course `@Get("/plaintext", produces = [MediaType.TEXT_HTML])` can be used in most cases for now. But browsers would probably try to render HTML tags if they find any :-). (And they use their default HTML styling instead of nice monospaced plaintext styling ;-))

### Environment Information
- **Operating System**: Windows
- **Micronaut Version:** 1.3.5
- **JDK Version:** 1.8

**Comment by lpellegr** [comment]
I experienced a similar issue with a need for `MediaType.APPLICATION_XML`. It would be really great to have a solution that does not require forking the rendering code. Or at least, having the provided renderers annotated for HTML, plain text, and XML support.

**Comment by sdelamo** [comment]
I think this is closed via https://github.com/micronaut-projects/micronaut-views/pull/265
