### ISSUE TITLE
JStachio support

### ISSUE THREAD

**Issue by agentgt** [micronaut-projects/micronaut-views#571]
### Feature description

I am the author of a templating language called JStachio.

https://github.com/jstachio/jstachio

I can provide integration with Micronaut but I'm unclear if it is better put the project/module here or should I host it in my own project like I have done with Spring and Dropwizard?

**Comment by graemerocher** [comment]
Up to you. If you contribute here you would be expected to maintain it

**Comment by agentgt** [comment]
I added a PR #574 

It mostly builds but for some reason I'm getting an exception with `findBaseline` gradle plugin which I think is because `view-jstachio` does not have any previous released versions.

I'm not sure how to override it or if I did something wrong.

**Comment by sdelamo** [comment]
added support via https://github.com/micronaut-projects/micronaut-views/pull/590
