### ISSUE TITLE
Passing a List as the model to ModelAndView results in an IntrospectionException

### ISSUE THREAD

**Issue by sbreakey** [micronaut-projects/micronaut-views#587]
### Expected Behavior

I was passing a `List<Whatever>` as the model to the `ModelAndView` constructor. Even if `Whatever` is annotated with `@Introspected` an `IntrospectionException` would be thrown telling me to annotate `ArrayList` with `@Introspected`, which is obviously not accurate.

As I understand it this was a mistake on my part as Thymeleaf templates require a String to be used as the key to identify different pieces of the model from within the view. e.g. in spring it's typically done like the below, where `messages` is the key that is used in the template to iterate over the list.

```
    public String messages(Model model) {
        model.addAttribute("messages", messageRepository.findAll());
        model.addAttribute("somethingElse", getSomethingElse());
        return "message/list";
    }
```

If I change my implementation to pass a Map as the model, it works fine, e.g.

```
    @Get("/")
    public ModelAndView messages() {
        var model = Map.of(
            "messages", messageRepository.findAll()
        );
        return new ModelAndView<>("index", model);
    }
```

### Actual Behaviour

An exception is thrown, stating:

```
19:49:42.042 [default-nioEventLoopGroup-1-2] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: No bean introspection available for type [class java.util.ArrayList]. Ensure the class is annotated with io.micronaut.core.annotation.Introspected
io.micronaut.core.beans.exceptions.IntrospectionException: No bean introspection available for type [class java.util.ArrayList]. Ensure the class is annotated with io.micronaut.core.annotation.Introspected
```

### Steps To Reproduce

1. add micronaut-views-thymeleaf as a dependency
2. Define a controller like the below, then try to trigger it.
3. It is irrelevant if Entry is annotated with @Introspected

```
    @Get("/")
    public ModelAndView<List<Entry>> index() {
        List<Entry> entries = new ArrayList<>();
        entries.add(new Entry(1, "title1"));
        entries.add(new Entry(2, "title2"));
        return new ModelAndView<>("index",  entries);
    }
```

### Environment Information

- OS: MacOS 12.6.7
- Java version: openjdk 17.0.8 2023-07-18
OpenJDK Runtime Environment Homebrew (build 17.0.8+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.8+0, mixed mode, sharing)

### Version

4.0.2

**Comment by timyates** [comment]
Investigating...  A workaround seems to be to wrap your list in a class, ie:

```
@Serdeable
public class MyWrapper<T> {

    private final List<T> entries;

    public MyWrapper(List<T> entries) {
        this.entries = entries;
    }

    public List<T> getEntries() {
        return entries;
    }
}
```

And then

```
        return new ModelAndView<>("index",  new MyWrapper<>(entries));

**Comment by timyates** [comment]
After some investigation I don't believe we can support using a List or Collection as a model for a view.

As far as I can tell, the templating libraries require a model with a structure such as a map, or object with fields.

If you require a List in the model, this can be wrapped in a Map or Custom object.

I have switched https://github.com/micronaut-projects/micronaut-views/pull/607 to document this restriction, but for now I don't think a code change is required
