### ISSUE TITLE
GraalVM: Collections in Pebble Views don't work in Micronaut 4

### ISSUE THREAD

**Issue by saw303** [micronaut-projects/micronaut-views#628]
### Expected Behavior

Given the following Pepple view `home2.html`

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Pebble</title>
    <meta charset="utf-8">
</head>
<body>
    <p>What are the numbers? {{ numbers }}</p>
    {% if numbers.size() > 0 %}
    <h1>Hurray, we've got numbers!</h1>
    {% else %}
    <h1>No numbers. Sorry dude.</h1>
    {% endif %}
</body>
</html>
```
and this controller

```java
@Controller("/views")
public class ViewsController {

    @Get("/pebble")
    public ModelAndView<Map<String, Object>> pebble2() {
        Map<String, Object> map = new HashMap<>();
        List<Integer> numbers = new ArrayList<>();
        numbers.add(1);
        numbers.add(2);
        numbers.add(3);
        numbers.add(4);
        map.put("numbers", numbers);
        return new ModelAndView<>("pebble/home2", map);
    }
}
```
I would expect the following output when accessing the view on `http://localhost:8080/views/pebble2` and running the application as a native image.

![CleanShot 2023-10-25 at 13 30 38@2x](https://github.com/micronaut-projects/micronaut-core/assets/71073/ed0c3560-3bbc-468b-b82a-edc90558ead8)

### Actual Behaviour

Running the native image, I get the following output. Method calls such as `size()` to my `numbers` collection are not working.

![CleanShot 2023-10-25 at 13 34 22@2x](https://github.com/micronaut-projects/micronaut-core/assets/71073/2be094ba-84fc-4be4-9358-6ac298f3aba1)

### Steps To Reproduce

- Checkout the following [commit](https://github.com/saw303/micronaut-pebbleviews-nativeimage/commit/f93850dbeaeb67cbe284a0aa2c3b26ac85c791fe) from branch `pebble` of [repository](https://github.com/saw303/micronaut-pebbleviews-nativeimage) 
- Run `./gradlew dockerBuild dockerBuildNative`
- Start a Docker container of the Fat Jar version `docker run -it --name fatjar -p 8080:8080 ghcr.io/saw303/nativeimagepebbleview:dummy`
- Start a Docker container of the native image version `docker run -it --name nativeimage -p 8081:8080 ghcr.io/saw303/nativeimagepebbleview:dummy-native`
- Compare the HTML output
   - http://localhost:8080/views/pebble2 <- That's the expected output
   - http://localhost:8081/views/pebble2

### Environment Information

- macOS 14.0
- Java 17

### Example Application

https://github.com/saw303/micronaut-pebbleviews-nativeimage

### Version

4

**Comment by sdelamo** [comment]
I don't think it will depend from user application to user application. the best way is generate the [necessary reflection metadata with the GraalVM Tracing agent](https://guides.micronaut.io/latest/micronaut-graalvm-reflection-gradle-java.html#generating-reflection-metadata-with-graalvm-tracing-agent).
