### ISSUE TITLE
work towards getting rid of HttpServerFilter in Micronaut Views

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-views#652]
https://github.com/micronaut-projects/micronaut-views/blob/master/views-core/src/main/java/io/micronaut/views/ViewsFilter.java

https://github.com/micronaut-projects/micronaut-views/pull/631

**Comment by timyates** [comment]
Done in https://github.com/micronaut-projects/micronaut-views/pull/712
