### ISSUE TITLE
Integrate with HTMX

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-views#660]
https://htmx.org

https://github.com/wimdeblauwe/htmx-spring-boot

**Comment by gijsleussink** [comment]
An example of HTMX with Thymeleaf integration in Spring Boot:
* [Talk by Wim de Blauwe](https://www.youtube.com/watch?v=POK4Zp1oRN8)
* [Spring Petclinic with HTMX and Thymeleaf](http://github.com/wimdeblauwe/spring-petclinic-htmx) (uses his convenience library [htmx-spring-boot](https://github.com/wimdeblauwe/htmx-spring-boot))

**Comment by KangoV** [comment]
I think for this it should be generic enough to support multiple template engines. But this is sorely needed for Micronaut.

**Comment by sdelamo** [comment]
@KangoV it will support every template engine we support (Thymeleaf, handlebars, JTE ...). I am going to work on this to have it ready for Micronaut Framework 4.4.0
