### ISSUE TITLE
No charset encoding specified on view responses

### ISSUE THREAD

**Issue by mikehearn** [micronaut-projects/micronaut-views#752]
### Expected Behavior

Unless otherwise specified, HTTP responses from Micronaut (Views) should declare that they are in UTF-8 in the `Content-Type` header.

### Actual Behaviour

No encoding is specified, leaving the browser to guess, and sometimes it guesses wrong. 

### Steps To Reproduce

1. Make a view that includes the output of something like `DateTimeFormatter.ofLocalizedDateTime(FormatStyle.MEDIUM).format(LocalDateTime.now())` which should yield a unicode NNBSP character before the "AM" or "PM" part.
2. Load it in Chrome.
3. Observe mojibake
4. Add a `<meta charset="utf-8"/>` tag to the header.
5. Observe that it's now fixed.

### Environment Information

macOS 14, Chrome

### Version

4.3.6

**Comment by timyates** [comment]
Done in https://github.com/micronaut-projects/micronaut-views/pull/801 for Micronaut 4.5.0
