### ISSUE TITLE
Consider using virtual threads for Java 21+

### ISSUE THREAD

**Issue by schneidersteve** [micronaut-projects/micronaut-views#757]
### Feature description

According to the documentation:
"The views module provides support for view rendering on the server side and does so by rendering views on the **I/O thread pool** in order to avoid blocking the Netty event loop."

**Comment by timyates** [comment]
This was fixed in Micronaut 4.4.1 and will be fixed for Micronaut 4.3.9 if we release one (micronaut-core [4.3.16](https://github.com/micronaut-projects/micronaut-core/releases/tag/v4.3.16) and [4.4.4](https://github.com/micronaut-projects/micronaut-core/releases/tag/v4.4.4))
