### ISSUE TITLE
Minor Issue With Link In Docs

### ISSUE THREAD

**Issue by jeffscottbrown** [micronaut-projects/micronaut-views#785]
### Issue description

At [micronaut-projects.github.io/micronaut-views/5.2.0/guide/#outOfBandSwaps](https://micronaut-projects.github.io/micronaut-views/5.2.0/guide/#outOfBandSwaps) is the following:

> You can return an API:views.htmx.HtmxResponse[] in a controller method to render multiple views in a single HTMX response...

It looks like `API:views.htmx.HtmxResponse[]` was intended to be a link to the api docs for HtmxResponse.

**Comment by sdelamo** [comment]
@wetted I guess the only think need it to replace: 

```
API:views.htmx.HtmxResponse[]
```
with: 
```
api:views.htmx.HtmxResponse[]
```

Please, test it locally.
